apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAjyFrstjzKeG4DlJxZnYCjVW0XzuHA/4VVf6P1yx3hJahwxrGUhME57etAm8FU1HIk4vsGhdKTHRdX6yLmG08gHsVvAQTb2FNkO89nZOQem+JmE7KZ5CZTqf71RgPdVDnnvLE9DNOjZm6TdS4SmJVLf0DSJ1AoXjkpp4SinmZQjgBqfm9kJkUysFis2akrTV+24pEabryOrB81xXPrFmZeF5iREbDaQC3kZ0I6zRXddcfxQ1Ey+niPHjDxBoepiurxj/TdWWTM1HS1HRfJaOpDG8BOizMnC9vZo+4SUNNPpdx2iVgnl9ze0e5lC3q09Xi/RQs/+owBW0PJPn/q+/bjHbHyUF6HwLbs9RRP+8ngWnusMAdq3Ov7GgDrCTRuTYC0a9VNMOj8HJXXb3kxyVszZo8ADjahanVpqluHnaS1RTJVya5QhYo89e749gk1HKKLDwuD5CusUt9YBnjedXoh1isgXjFbSn7XBi/qJrc6+JMzTZMHAzGj+houa6ZSixe63/MIrI2G8WeMYdGB/20bpvvgtZgaWdEsI6jSReR0Ey5THlFXcR7LWIizflkzYPUaPQEJdsCCkLk16LhnUt/KMb7DANeZ3x9j037Thn8Y6PKgZa61/4EOQNbTAZocqYH1+SqpRCofWboJ+3eFRrpSaMkjP2ErME39F2mrfBgf09cx1mWHiVFMVfICrVXSqPU9M8M3LvXvqpuhuJD53kp/V88RoYhUeGrsYl3r1V+n2XqfyHNjHhEh
    username: AgC2d6jovnBjRua8lyMMu23AiX8Nin+fxZQf9o2YHdNkeKoAHGRcWsDxqhOIQRrFIXp5/TeaMEIAGKwLpLfITEx7j/5gydMStibT5qTKSSybtsyraoMLHRxAj7tsg9wzCysEZNY3WH7aHoBG1V53dsW+mRPzg2qoSB0JkOX51f5co66xHxREKfya56mdKxu7iFsbeNyyuslLvwE5Qbv5ADrYnAgA68SFbimCj6sxl/B78dTCKPmkLg4vLEAs4zzQgNXsrLO6aKMakTUgOS9wa6HeUPQDIEhjT0DzmCpTC0UK6L5ue/pyINM8fGgK/pp/gtqdbj4kd2S7n+oXwCRVvVaK0Ne/dTREE2zlZfvJoEFXgRe4WpNufR98O+nYLmE35l3FKNzG0s8vrEb16v26jmVaf/0tQcm+YQsIdH2KvTxfhl7dYTPO5SU/GmMfV6A4B1Nc3v7Tf3TU9RgMQgJkIdn+gmjx98YFzWuyhCYRgodGTn1QR7pKrjQmFYZ199rbbmhvAw5HTXTCzOLEk1wopm/fCXdzFbAHt/f8bcRjxapDI/r8jDFdVoPRaI8nxS07xZLHsJ803h22ZGyqVomDSgNuAjty2byvPTS4kgXN2XoW/2H1/jkIY4oZJREomR9DgjqKy2x4bGNs8tkEnszRviaKBUnEzCSMKWpjV8vinv7F/JcoytxFw5DJ9YVObNA2WwD5jFFKB3o=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

